default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  reconnect: true

development:
  <<: *default
  host: localhost
  database: td_dev
  username: td
  password: travellersdiary

test:
  <<: *default
  host: localhost
  database: td_test
  username: td
  password: travellersdiary

production:
  <<: *default
  url: <%= ENV.fetch("DATABASE_URL") %>
